"""
Master generation pipeline for Damabiah content:
  1. Portrait image    (Z-Image-Turbo)
  2. Sigil image       (Z-Image-Turbo)
  3. Devotional song   (ACE Step 1.5)
  4. Speech audio      (ACE Step 1.5 — spoken word)
  5. Video             (LTX 2.3 image+audio → video)

Uses _graph_to_api() from our MCP server to convert saved workflows.
"""
import sys, json, urllib.request, time, os, random, uuid
from pathlib import Path

COMFY = "http://127.0.0.1:8000"
OUTPUT_DIR = os.path.join(os.path.dirname(__file__), "test", "damabiah")
os.makedirs(OUTPUT_DIR, exist_ok=True)

# Pre-converted LTX API workflow (generated by _convert_ltx.py)
LTX_API_PATH = os.path.join(os.path.dirname(__file__), "_ltx_api.json")


# ── Helpers ────────────────────────────────────────────────────────────────────

def submit_workflow(api_workflow):
    """Submit an API-format workflow and return prompt_id."""
    payload = json.dumps({"prompt": api_workflow}).encode()
    req = urllib.request.Request(
        f"{COMFY}/api/prompt",
        data=payload,
        headers={"Content-Type": "application/json"},
    )
    resp = urllib.request.urlopen(req)
    data = json.loads(resp.read())
    return data["prompt_id"]


def wait_for_completion(prompt_id, timeout_polls=180):
    """Poll until prompt completes. Return the outputs dict or raise."""
    print(f"  Waiting for {prompt_id}...")
    for i in range(timeout_polls):
        time.sleep(2)
        try:
            resp = urllib.request.urlopen(f"{COMFY}/api/history/{prompt_id}")
            history = json.loads(resp.read())
        except Exception:
            continue

        if prompt_id not in history:
            if i % 10 == 9:
                print(f"    poll {i+1}…")
            continue

        entry = history[prompt_id]
        status = entry.get("status", {})
        if status.get("status_str") == "error":
            msgs = status.get("messages", [])
            raise RuntimeError(f"Generation error: {msgs}")

        return entry.get("outputs", {})

    raise TimeoutError(f"Timed out waiting for {prompt_id}")


def download_image(outputs, node_id, dest):
    """Download a SaveImage output to disk."""
    images = outputs.get(node_id, {}).get("images", [])
    if not images:
        raise ValueError(f"No images in node {node_id} output")
    img = images[0]
    url = f"{COMFY}/api/view?filename={img['filename']}&subfolder={img.get('subfolder','')}&type=output"
    resp = urllib.request.urlopen(url)
    with open(dest, "wb") as f:
        f.write(resp.read())
    print(f"  Saved: {dest}")


def download_audio(outputs, node_id, dest):
    """Download a SaveAudio output to disk."""
    # Audio outputs can be in 'audio' or 'results' key
    for key in ["audio", "results"]:
        items = outputs.get(node_id, {}).get(key, [])
        if items:
            break
    if not items:
        # Dump what we got
        print(f"  Available output keys for node {node_id}: {list(outputs.get(node_id, {}).keys())}")
        print(f"  Full output: {json.dumps(outputs.get(node_id, {}), indent=2)[:500]}")
        raise ValueError(f"No audio in node {node_id} output")
    item = items[0]
    fn = item.get("filename", "")
    sf = item.get("subfolder", "")
    # For audio, the type might be 'output' or 'temp'
    ftype = item.get("type", "output")
    url = f"{COMFY}/api/view?filename={fn}&subfolder={sf}&type={ftype}"
    resp = urllib.request.urlopen(url)
    with open(dest, "wb") as f:
        f.write(resp.read())
    print(f"  Saved: {dest}")


def download_video(outputs, dest):
    """Download a SaveVideo output — search all nodes for video/gifs/animated images."""
    for nid, out in outputs.items():
        for key in ["videos", "gifs", "results", "images"]:
            items = out.get(key, [])
            if items:
                item = items[0]
                fn = item.get("filename", "")
                # Check it's actually a video (animated or .mp4)
                if key == "images" and not (out.get("animated") or fn.endswith(".mp4")):
                    continue
                sf = item.get("subfolder", "")
                ftype = item.get("type", "output")
                url = f"{COMFY}/api/view?filename={fn}&subfolder={sf}&type={ftype}"
                resp = urllib.request.urlopen(url)
                with open(dest, "wb") as f:
                    f.write(resp.read())
                print(f"  Saved: {dest}")
                return
    raise ValueError("No video found in outputs")


def upload_to_comfyui(filepath):
    """Upload a file to ComfyUI's input directory via multipart POST."""
    boundary = uuid.uuid4().hex
    filename = Path(filepath).name
    with open(filepath, "rb") as f:
        file_data = f.read()
    parts = [
        f"--{boundary}".encode(),
        f'Content-Disposition: form-data; name="image"; filename="{filename}"'.encode(),
        b"Content-Type: application/octet-stream",
        b"",
        file_data,
        f"--{boundary}".encode(),
        b'Content-Disposition: form-data; name="type"',
        b"",
        b"input",
        f"--{boundary}".encode(),
        b'Content-Disposition: form-data; name="overwrite"',
        b"",
        b"true",
        f"--{boundary}--".encode(),
    ]
    body = b"\r\n".join(parts)
    req = urllib.request.Request(
        f"{COMFY}/upload/image",
        data=body,
        headers={"Content-Type": f"multipart/form-data; boundary={boundary}"},
        method="POST",
    )
    resp = urllib.request.urlopen(req, timeout=30)
    result = json.loads(resp.read())
    print(f"  Uploaded: {filename} -> {result}")
    return result


# ── Z-Image workflow builder ──────────────────────────────────────────────────

def build_zimage_api(prompt_text, prefix, width=1024, height=1024):
    """Build a correct Z-Image-Turbo API workflow."""
    return {
        "28": {
            "class_type": "UNETLoader",
            "inputs": {"unet_name": "z_image_turbo_bf16.safetensors", "weight_dtype": "default"}
        },
        "30": {
            "class_type": "CLIPLoader",
            "inputs": {"clip_name": "qwen_3_4b.safetensors", "type": "lumina2", "device": "default"}
        },
        "27": {
            "class_type": "CLIPTextEncode",
            "inputs": {"text": prompt_text, "clip": ["30", 0]}
        },
        "33": {
            "class_type": "ConditioningZeroOut",
            "inputs": {"conditioning": ["27", 0]}
        },
        "11": {
            "class_type": "ModelSamplingAuraFlow",
            "inputs": {"shift": 3, "model": ["28", 0]}
        },
        "13": {
            "class_type": "EmptySD3LatentImage",
            "inputs": {"width": width, "height": height, "batch_size": 1}
        },
        "3": {
            "class_type": "KSampler",
            "inputs": {
                "seed": random.randint(0, 2**63),
                "steps": 8, "cfg": 1,
                "sampler_name": "res_multistep", "scheduler": "simple",
                "denoise": 1,
                "model": ["11", 0], "positive": ["27", 0],
                "negative": ["33", 0], "latent_image": ["13", 0]
            }
        },
        "29": {
            "class_type": "VAELoader",
            "inputs": {"vae_name": "ae.safetensors"}
        },
        "8": {
            "class_type": "VAEDecode",
            "inputs": {"samples": ["3", 0], "vae": ["29", 0]}
        },
        "9": {
            "class_type": "SaveImage",
            "inputs": {"filename_prefix": prefix, "images": ["8", 0]}
        }
    }


# ── ACE Step audio workflow builder ───────────────────────────────────────────

def build_ace_step_api(tags, lyrics, prefix, seed=None, bpm=120, duration=120.0, language="en",
                       keyscale="A minor", timesignature="4"):
    """Build ACE Step 1.5 split 4B API workflow."""
    if seed is None:
        seed = random.randint(0, 2**63)
    return {
        "104": {
            "class_type": "UNETLoader",
            "inputs": {"unet_name": "acestep_v1.5_turbo.safetensors", "weight_dtype": "default"}
        },
        "106": {
            "class_type": "VAELoader",
            "inputs": {"vae_name": "ace_1.5_vae.safetensors"}
        },
        "105": {
            "class_type": "DualCLIPLoader",
            "inputs": {
                "clip_name1": "qwen_0.6b_ace15.safetensors",
                "clip_name2": "qwen_4b_ace15.safetensors",
                "type": "ace",
                "device": "default"
            }
        },
        "94": {
            "class_type": "TextEncodeAceStepAudio1.5",
            "inputs": {
                "tags": tags,
                "lyrics": lyrics,
                "seed": seed,
                "control_after_generate": "fixed",
                "bpm": bpm,
                "duration": float(duration),
                "timesignature": timesignature,
                "language": language,
                "keyscale": keyscale,
                "generate_audio_codes": True,
                "cfg_scale": 2.0,
                "temperature": 0.85,
                "top_p": 0.9,
                "top_k": 0,
                "min_p": 0.0,
                "clip": ["105", 0]
            }
        },
        "98": {
            "class_type": "EmptyAceStep1.5LatentAudio",
            "inputs": {"seconds": float(duration), "batch_size": 1}
        },
        "47": {
            "class_type": "ConditioningZeroOut",
            "inputs": {"conditioning": ["94", 0]}
        },
        "78": {
            "class_type": "ModelSamplingAuraFlow",
            "inputs": {"shift": 3, "model": ["104", 0]}
        },
        "3": {
            "class_type": "KSampler",
            "inputs": {
                "seed": seed,
                "control_after_generate": "fixed",
                "steps": 8,
                "cfg": 1,
                "sampler_name": "euler",
                "scheduler": "simple",
                "denoise": 1,
                "model": ["78", 0],
                "positive": ["94", 0],
                "negative": ["47", 0],
                "latent_image": ["98", 0]
            }
        },
        "18": {
            "class_type": "VAEDecodeAudio",
            "inputs": {"samples": ["3", 0], "vae": ["106", 0]}
        },
        "107": {
            "class_type": "SaveAudioMP3",
            "inputs": {"filename_prefix": prefix, "quality": "V0", "audio": ["18", 0]}
        }
    }


# ══════════════════════════════════════════════════════════════════════════════
# MAIN PIPELINE
# ══════════════════════════════════════════════════════════════════════════════

if __name__ == "__main__":
    import argparse
    parser = argparse.ArgumentParser()
    parser.add_argument("--step", type=int, default=0,
                        help="Run only step N (1=portrait, 2=sigil, 3=song, 4=speech, 5=video). 0=all")
    args = parser.parse_args()

    # ── Step 1: Damabiah Portrait ──────────────────────────────────────────
    if args.step in (0, 1):
        print("\n" + "="*60)
        print("STEP 1: Generating Damabiah Portrait")
        print("="*60)
        portrait_prompt = (
            "Damabiah depicted as a sacred luminous being within the atmosphere of "
            "star-water, vessel of futurity, lucid transmission, ritual cinematic realism, "
            "elegant presence, archetypal rather than generic fantasy, posture conveying "
            "blessing and intelligent force. Aquarius energy, deep indigo aura with silver "
            "and pale gold accents, streams of starlight water cascading around the figure, "
            "ceremonial robes with geometric patterns, cosmic background with constellation "
            "of Aquarius visible, volumetric light, atmospheric depth, photorealistic, 8k detail"
        )
        wf = build_zimage_api(portrait_prompt, "damabiah_portrait", 1024, 1024)
        pid = submit_workflow(wf)
        outputs = wait_for_completion(pid)
        download_image(outputs, "9", os.path.join(OUTPUT_DIR, "damabiah_portrait.png"))

    # ── Step 2: Damabiah Sigil ─────────────────────────────────────────────
    if args.step in (0, 2):
        print("\n" + "="*60)
        print("STEP 2: Generating Damabiah Sigil")
        print("="*60)
        sigil_prompt = (
            "A clean ceremonial sigil for the angel Damabiah, sacred geometry expressing "
            "blessing, order, and the current of Aquarius, suitable for parchment or "
            "seal-page presentation. Crisp black linework on aged cream parchment, "
            "geometric precision, interlocking circles and triangles forming a symmetrical "
            "mandala-like seal, Hebrew letterforms subtly integrated, wavy Aquarius water "
            "lines flowing through the geometry, no color except gold leaf accents on key "
            "nodes, grimoire illustration style, high contrast, clean edges, 8k detail"
        )
        wf = build_zimage_api(sigil_prompt, "damabiah_sigil", 1024, 1024)
        pid = submit_workflow(wf)
        outputs = wait_for_completion(pid)
        download_image(outputs, "9", os.path.join(OUTPUT_DIR, "damabiah_sigil.png"))

    # ── Step 3: Devotional Song (ACE Step 1.5) ────────────────────────────
    if args.step in (0, 3):
        print("\n" + "="*60)
        print("STEP 3: Generating Damabiah Devotional Hymn")
        print("="*60)
        tags = (
            "Ritual ambient, chamber sacred, occult devotional, "
            "clear, visionary, spacious, intelligent, "
            "numinous, emotionally precise, archetypal, "
            "close-mic lead with restrained choir on refrains, "
            "felt piano, frame drum pulse, warm strings, bell or chime accents, low drone, "
            "60 BPM"
        )
        lyrics = (
            "[Invocation]\n"
            "Damabiah of clear blessing, enter the breath and steady the heart.\n\n"
            "[Verse 1]\n"
            "The sign is Aquarius, the stage is Return with the Elixir, "
            "and the body is learning a wiser way to carry this current.\n"
            "What once felt fated can become chosen when I stay inside the rhythm "
            "long enough to hear what is true.\n\n"
            "[Chorus]\n"
            "DAMABIAH, DRAW ME INTO THE TRUE CENTER OF THIS DECAN.\n"
            "LET THIS CURRENT BECOME SOMETHING I CAN FEEL AND PRACTICE.\n\n"
            "[Verse 2]\n"
            "Through 7 of Swords, through Salt, through the letter Mem, "
            "let the old pattern become usable wisdom.\n"
            "I welcome the lesson without collapsing into performance or refusal.\n\n"
            "[Bridge]\n"
            "The element is Air, the work is Return with the Elixir, "
            "and the nervous system is allowed to learn by repetition rather than force.\n\n"
            "[Final Chorus]\n"
            "DAMABIAH, STAY NEAR ENOUGH TO BECOME AN EMBODIED PATTERN.\n"
            "LET THIS SONG TURN SYMBOL INTO PRACTICE.\n\n"
            "[Benediction]\n"
            "By this hymn, the current of Damabiah is welcomed in right relationship."
        )
        wf = build_ace_step_api(
            tags=tags,
            lyrics=lyrics,
            prefix="damabiah_hymn",
            bpm=62,
            duration=120.0,
            language="en",
            keyscale="A minor",
            timesignature="4"
        )
        pid = submit_workflow(wf)
        outputs = wait_for_completion(pid, timeout_polls=300)
        download_audio(outputs, "107", os.path.join(OUTPUT_DIR, "damabiah_hymn.mp3"))

    # ── Step 4: Spoken Benediction (ACE Step 1.5 — spoken word) ────────────
    if args.step in (0, 4):
        print("\n" + "="*60)
        print("STEP 4: Generating Damabiah Spoken Benediction")
        print("="*60)
        speech_tags = (
            "Spoken word, male voice, deep resonant, ritual invocation, "
            "reverb cathedral space, slow pace, contemplative, sacred, "
            "clear diction, solo voice, no music, no instruments, "
            "close-mic, intimate, 60 BPM"
        )
        speech_lyrics = (
            "[Invocation]\n"
            "I am Damabiah, angel of the third decan of Aquarius.\n"
            "I am the fountain of wisdom that never runs dry.\n\n"
            "[Verse 1]\n"
            "I move through the current of air and water,\n"
            "bringing clarity to those who seek without force.\n"
            "The old patterns dissolve in my presence.\n"
            "What remains is the truth you were always carrying.\n\n"
            "[Verse 2]\n"
            "I am the blessing that arrives before you name it.\n"
            "I am the stillness inside the turning wheel.\n"
            "Let the nervous system rest.\n"
            "Let the breath become a vessel.\n\n"
            "[Benediction]\n"
            "By this voice, the current of Damabiah is made present.\n"
            "Go now, and carry this frequency in your body."
        )
        wf = build_ace_step_api(
            tags=speech_tags,
            lyrics=speech_lyrics,
            prefix="damabiah_speech",
            bpm=60,
            duration=30.0,
            language="en",
            keyscale="A minor",
            timesignature="4"
        )
        pid = submit_workflow(wf)
        outputs = wait_for_completion(pid, timeout_polls=300)
        download_audio(outputs, "107", os.path.join(OUTPUT_DIR, "damabiah_speech.mp3"))

    # ── Step 5: LTX Video (portrait + speech → video) ─────────────────────
    if args.step in (0, 5):
        print("\n" + "="*60)
        print("STEP 5: Generating Damabiah Video (LTX 2.3 i+a2v)")
        print("="*60)

        portrait_path = os.path.join(OUTPUT_DIR, "damabiah_portrait.png")
        speech_path = os.path.join(OUTPUT_DIR, "damabiah_speech.mp3")

        if not os.path.exists(portrait_path):
            raise FileNotFoundError(f"Run step 1 first: {portrait_path}")
        if not os.path.exists(speech_path):
            raise FileNotFoundError(f"Run step 4 first: {speech_path}")

        # Upload portrait and speech to ComfyUI input directory
        print("  Uploading portrait image...")
        img_result = upload_to_comfyui(portrait_path)
        img_filename = img_result.get("name", "damabiah_portrait.png")

        print("  Uploading speech audio...")
        audio_result = upload_to_comfyui(speech_path)
        audio_filename = audio_result.get("name", "damabiah_speech.mp3")

        # Load pre-converted LTX API workflow
        with open(LTX_API_PATH, "r") as f:
            ltx_api = json.load(f)

        # Patch inputs:
        # 269: LoadImage — set our portrait
        ltx_api["269"]["inputs"]["image"] = img_filename

        # 276: LoadAudio — set our speech audio
        ltx_api["276"]["inputs"]["audio"] = audio_filename

        # 340:319: PrimitiveStringMultiline (Prompt) — video description
        # Keep it simple and action-focused — LTX lip-syncs better with natural
        # descriptions than over-detailed anatomical cues.
        ltx_api["340:319"]["inputs"]["value"] = (
            "sacred luminous being speaks a solemn invocation as camera slowly zooms in "
            "on the face as indigo and silver light radiates and streams of starlight "
            "water cascade slowly around the ceremonial robes"
        )

        # 340:314: CLIPTextEncode (negative) — keep standard negatives
        ltx_api["340:314"]["inputs"]["text"] = (
            "ugly, blurry, low quality, distorted, cartoon, anime, "
            "fast motion, shaky camera, text overlay, watermark"
        )

        # 340:331: Duration — match speech length (seconds)
        ltx_api["340:331"]["inputs"]["value"] = 9.0

        # 340:323: Frame rate
        ltx_api["340:323"]["inputs"]["value"] = 24

        # 340:324: Height  (1280x720 needed for lip-sync detail)
        ltx_api["340:324"]["inputs"]["value"] = 720

        # 340:330: Width
        ltx_api["340:330"]["inputs"]["value"] = 1280

        # 340:305: Switch to text-to-video? — False (we want image+audio to video)
        ltx_api["340:305"]["inputs"]["value"] = False

        # 341: SaveVideo — set output prefix
        ltx_api["341"]["inputs"]["filename_prefix"] = "damabiah_video"

        # Update random seeds
        seed = random.randint(0, 2**63)
        ltx_api["340:285"]["inputs"]["noise_seed"] = seed
        ltx_api["340:286"]["inputs"]["noise_seed"] = seed

        pid = submit_workflow(ltx_api)
        outputs = wait_for_completion(pid, timeout_polls=600)
        download_video(outputs, os.path.join(OUTPUT_DIR, "damabiah_video.mp4"))

    print("\n" + "="*60)
    print("ALL STEPS COMPLETE")
    print(f"Output directory: {OUTPUT_DIR}")
    print("="*60)
